"use strict";

// One distinct task form per entry; values stay friendly for mental arithmetic.
const L = (level, basis, training, plus) => ({ basis, training, plus })[level];
const N = (value) => shortNumber(value, 2);
const E = (title, question, answer, unit, hint, formula, calculation, diagram = "", decimals = Number.isInteger(answer) ? 0 : 2) =>
  taskBase(title, question, answer, unit, decimals,
    [hint, formula, "Setze die gegebenen Zahlen ein und prüfe die Einheit."],
    [formula, `${calculation} = ${formatNumber(answer, decimals)} ${unit}`], diagram);

const EXTRA_TEMPLATES = {
  grund: [
    (_, level) => { const [a, b] = L(level, [80, 25], [140, 45], [260, 75]); return E("Differenz im Kopf", `Berechne <strong>${a} − ${b}</strong>.`, a-b, "", "Zerlege den zweiten Wert in Zehner und Einer.", "Differenz = Startwert − Abzug", `${a} − ${b}`); },
    (_, level) => { const [a, b] = L(level, [1.2, 0.5], [2.4, 1.5], [3.75, 1.25]); return E("Dezimalzahlen addieren", `Berechne <strong>${N(a)} + ${N(b)}</strong>.`, a+b, "", "Schreibe die Kommas gedanklich untereinander.", "Summe = erster Wert + zweiter Wert", `${N(a)} + ${N(b)}`); },
    (_, level) => { const [a, b] = L(level, [4.5, 1.2], [8.75, 2.5], [12.5, 3.75]); return E("Dezimalzahlen abziehen", `Berechne <strong>${N(a)} − ${N(b)}</strong>.`, a-b, "", "Rechne erst die ganzen Zahlen, dann die Nachkommastellen.", "Differenz = erster Wert − zweiter Wert", `${N(a)} − ${N(b)}`); },
    (_, level) => { const a = L(level, 2.5, 3.75, 12.5); return E("Mit zehn multiplizieren", `Berechne <strong>${N(a)} · 10</strong>.`, a*10, "", "Das Komma wandert eine Stelle nach rechts.", "Zehnfacher Wert = Wert · 10", `${N(a)} · 10`); },
    (_, level) => { const [part, total] = L(level, [1, 2], [3, 4], [2, 5]); const length = L(level, 80, 120, 150); return E("Anteil einer Länge", `Wie viel Millimeter sind <strong>${part}/${total}</strong> von <strong>${length} mm</strong>?`, length*part/total, "mm", "Teile die Länge zuerst durch den Nenner.", "Anteil = Gesamtlänge · Zähler / Nenner", `${length} · ${part}/${total}`); },
    (_, level) => { const [a, b, d] = L(level, [3, 1, 4], [7, 3, 8], [9, 5, 10]); return E("Bruch abziehen", `Berechne <strong>${a}/${d} − ${b}/${d}</strong> als Dezimalzahl.`, (a-b)/d, "", "Bei gleichem Nenner ziehst du nur die Zähler ab.", "Differenz = (erster Zähler − zweiter Zähler) / Nenner", `(${a} − ${b})/${d}`); },
    (_, level) => { const [n, d] = L(level, [6, 8], [9, 12], [15, 20]); return E("Bruch kürzen", `Kürze <strong>${n}/${d}</strong> und gib den Wert als Dezimalzahl an.`, n/d, "", "Zähler und Nenner dürfen durch dieselbe Zahl geteilt werden.", "Bruchwert = Zähler / Nenner", `${n}/${d}`); },
    (_, level) => { const [a, b] = L(level, [48, 6], [72, 8], [96, 12]); return E("Division prüfen", `Berechne <strong>${a} : ${b}</strong>.`, a/b, "", "Frage dich: Welche Zahl mal Divisor ergibt den Dividend?", "Quotient = Dividend / Divisor", `${a} : ${b}`); },
    (_, level) => { const [n, a, b] = L(level, [4, 20, 5], [6, 30, 5], [8, 40, 5]); return E("Ausmultiplizieren", `Berechne <strong>${n} · (${a} + ${b})</strong>.`, n*(a+b), "", "Du kannst beide Summanden einzeln multiplizieren.", "n · (a + b) = n · a + n · b", `${n} · ${a} + ${n} · ${b}`); },
    (_, level) => { const a = L(level, 12.46, 18.74, 25.36); const answer = Math.round(a*10)/10; return E("Auf Zehntel runden", `Runde <strong>${N(a)} mm</strong> auf eine Stelle nach dem Komma.`, answer, "mm", "Sieh auf die zweite Stelle nach dem Komma.", "Ab 5 wird die erste Nachkommastelle erhöht.", `${N(a)} mm gerundet`, "", 1); },
    (_, level) => { const [ist, soll] = L(level, [19.8, 20], [24.7, 25], [34.85, 35]); return E("Abweichung vom Soll", `Ein Maß ist <strong>${N(ist)} mm</strong> lang. Sollmaß: <strong>${N(soll)} mm</strong>. Wie viel fehlt?`, soll-ist, "mm", "Ziehe das Istmaß vom Sollmaß ab.", "Fehlmaß = Sollmaß − Istmaß", `${N(soll)} − ${N(ist)}`); },
    (_, level) => { const [a, b, c] = L(level, [100, 4, 15], [150, 5, 20], [250, 6, 25]); return E("Mal vor Minus", `Berechne <strong>${a} − ${b} · ${c}</strong>.`, a-b*c, "", "Zuerst multiplizieren, danach abziehen.", "Punktrechnung vor Strichrechnung", `${a} − ${b*c}`); }
  ],
  einheiten: [
    (_, level) => { const x=L(level, 8, 12, 25); return E("Zentimeter in Millimeter", `Wandle <strong>${x} cm</strong> in mm um.`, x*10, "mm", "1 cm sind 10 mm.", "mm = cm · 10", `${x} · 10`); },
    (_, level) => { const x=L(level, 65, 125, 375); return E("Millimeter in Zentimeter", `Wandle <strong>${x} mm</strong> in cm um.`, x/10, "cm", "1 cm sind 10 mm.", "cm = mm / 10", `${x} / 10`); },
    (_, level) => { const x=L(level, 1.5, 2.5, 3.75); return E("Meter in Zentimeter", `Wandle <strong>${N(x)} m</strong> in cm um.`, x*100, "cm", "1 m sind 100 cm.", "cm = m · 100", `${N(x)} · 100`); },
    (_, level) => { const x=L(level, 2.5, 4.25, 7.5); return E("Kilogramm in Gramm", `Wandle <strong>${N(x)} kg</strong> in g um.`, x*1000, "g", "1 kg sind 1000 g.", "g = kg · 1000", `${N(x)} · 1000`); },
    (_, level) => { const x=L(level, 750, 1250, 2750); return E("Gramm in Kilogramm", `Wandle <strong>${x} g</strong> in kg um.`, x/1000, "kg", "1 kg sind 1000 g.", "kg = g / 1000", `${x} / 1000`); },
    (_, level) => { const x=L(level, 3, 7, 12); return E("Minuten in Sekunden", `Wandle <strong>${x} min</strong> in s um.`, x*60, "s", "Eine Minute hat 60 Sekunden.", "s = min · 60", `${x} · 60`); },
    (_, level) => { const x=L(level, 90, 150, 210); return E("Sekunden in Minuten", `Wandle <strong>${x} s</strong> in min um.`, x/60, "min", "Eine Minute hat 60 Sekunden.", "min = s / 60", `${x} / 60`); },
    (_, level) => { const x=L(level, 0.5, 1.25, 2.75); return E("Liter in Milliliter", `Wandle <strong>${N(x)} l</strong> in ml um.`, x*1000, "ml", "1 l sind 1000 ml.", "ml = l · 1000", `${N(x)} · 1000`); },
    (_, level) => { const x=L(level, 500, 1250, 2750); return E("Quadratmillimeter in Quadratzentimeter", `Wandle <strong>${x} mm²</strong> in cm² um.`, x/100, "cm²", "1 cm² sind 100 mm².", "cm² = mm² / 100", `${x} / 100`); },
    (_, level) => { const x=L(level, 2, 4.5, 7.25); return E("Kubikdezimeter in Kubikzentimeter", `Wandle <strong>${N(x)} dm³</strong> in cm³ um.`, x*1000, "cm³", "1 dm³ sind 1000 cm³.", "cm³ = dm³ · 1000", `${N(x)} · 1000`); },
    (_, level) => { const x=L(level, 36, 54, 72); return E("km/h in m/s", `Wandle <strong>${x} km/h</strong> in m/s um.`, x/3.6, "m/s", "Teile km/h durch 3,6.", "m/s = km/h / 3,6", `${x} / 3,6`); },
    (_, level) => { const x=L(level, 1.5, 2.25, 3.5); return E("Stunden in Minuten", `Wandle <strong>${N(x)} h</strong> in Minuten um.`, x*60, "min", "Eine Stunde hat 60 Minuten.", "min = h · 60", `${N(x)} · 60`); }
  ],
  prozent: [
    (_, level) => { const x=L(level, 80, 140, 260); return E("Zehn Prozent", `Wie viel sind <strong>10 %</strong> von <strong>${x} Teilen</strong>?`, x/10, "Teile", "10 % ist ein Zehntel.", "W = G · 10 / 100", `${x} / 10`); },
    (_, level) => { const x=L(level, 40, 120, 280); return E("Ein Viertel als Prozent", `Wie viele Stück sind <strong>25 %</strong> von <strong>${x}</strong>?`, x/4, "Stück", "25 % ist ein Viertel.", "W = G / 4", `${x} / 4`); },
    (_, level) => { const x=L(level, 60, 140, 320); return E("Die Hälfte", `Wie viele Kilogramm sind <strong>50 %</strong> von <strong>${x} kg</strong>?`, x/2, "kg", "50 % bedeutet die Hälfte.", "W = G / 2", `${x} / 2`); },
    (_, level) => { const x=L(level, 40, 80, 160); return E("Drei Viertel", `Wie viel sind <strong>75 %</strong> von <strong>${x} mm</strong>?`, x*3/4, "mm", "75 % sind drei Viertel.", "W = G · 3 / 4", `${x} · 3/4`); },
    (_, level) => { const [part,whole]=L(level,[10,50],[18,60],[35,140]); return E("Anteil in Prozent", `Von <strong>${whole}</strong> Werkstücken sind <strong>${part}</strong> markiert. Wie viel Prozent sind das?`, part/whole*100, "%", "Teile den Anteil durch die Gesamtzahl.", "p = Anteil / Ganzes · 100", `${part}/${whole} · 100`); },
    (_, level) => { const x=L(level, 20, 40, 80); return E("Zehn Prozent Zuschlag", `Ein Teil kostet <strong>${x} €</strong>. Dazu kommen <strong>10 %</strong>. Wie hoch ist der neue Preis?`, x*1.1, "€", "10 % von x sind x / 10.", "Neuer Preis = Preis + Zuschlag", `${x} + ${x/10}`); },
    (_, level) => { const [bad,all]=L(level,[5,100],[12,200],[18,300]); return E("Ausschussquote", `Von <strong>${all}</strong> Teilen sind <strong>${bad}</strong> Ausschuss. Berechne die Ausschussquote.`, bad/all*100, "%", "Ausschuss ist ein Anteil an allen Teilen.", "Quote = Ausschuss / Gesamtzahl · 100", `${bad}/${all} · 100`); },
    (_, level) => { const [actual,target]=L(level,[90,100],[180,200],[270,300]); return E("Fehlender Anteil", `Soll: <strong>${target}</strong> Teile. Fertig sind <strong>${actual}</strong>. Wie viel Prozent fehlen noch?`, (target-actual)/target*100, "%", "Erst die fehlenden Teile zählen.", "Fehlanteil = (Soll − Ist) / Soll · 100", `(${target} − ${actual})/${target} · 100`); },
    (_, level) => { const x=L(level, 100, 200, 300); return E("Mehrwertsteuer", `Ein Artikel kostet netto <strong>${x} €</strong>. Wie viel sind <strong>19 %</strong> Mehrwertsteuer?`, x*0.19, "€", "1 % von 100 € ist 1 €.", "Steuer = Nettopreis · 19 / 100", `${x} · 19/100`); },
    (_, level) => { const reduced=L(level, 80, 160, 240); return E("Preis vor Rabatt", `Nach <strong>20 % Rabatt</strong> kostet ein Werkzeug <strong>${reduced} €</strong>. Wie hoch war der alte Preis?`, reduced/0.8, "€", "Der neue Preis entspricht 80 %.", "Alter Preis = neuer Preis / 0,8", `${reduced} / 0,8`); },
    (_, level) => { const capital=L(level, 100, 200, 400); return E("Jahreszins", `Ein Guthaben von <strong>${capital} €</strong> wird ein Jahr mit <strong>5 %</strong> verzinst. Wie hoch sind die Zinsen?`, capital*0.05, "€", "5 % sind ein Zwanzigstel.", "Z = K · p / 100", `${capital} · 5/100`); },
    (_, level) => { const capital=L(level, 400, 800, 1200); return E("Zins für ein Vierteljahr", `Ein Guthaben von <strong>${capital} €</strong> wird mit <strong>4 % pro Jahr</strong> verzinst. Wie viel Zins gibt es für drei Monate?`, capital*0.01, "€", "Drei Monate sind ein Vierteljahr.", "Z = K · 4 / 100 · 3 / 12", `${capital} · 1/100`); }
  ],
  umstellen: [
    (_, level) => { const [v,t]=L(level,[4,5],[6,8],[12,15]); return E("Weg aus Geschwindigkeit", `Stelle <strong>v = s / t</strong> nach s um. Berechne den Weg bei v = <strong>${v} m/s</strong> und t = <strong>${t} s</strong>.`, v*t, "m", "Multipliziere beide Seiten mit t.", "s = v · t", `${v} · ${t}`); },
    (_, level) => { const [s,t]=L(level,[60,10],[144,12],[360,15]); return E("Geschwindigkeit freistellen", `Stelle <strong>s = v · t</strong> nach v um. Berechne v bei s = <strong>${s} m</strong> und t = <strong>${t} s</strong>.`, s/t, "m/s", "Teile beide Seiten durch t.", "v = s / t", `${s} / ${t}`); },
    (_, level) => { const [area,a]=L(level,[120,10],[360,15],[900,25]); return E("Breite freistellen", `Stelle <strong>A = a · b</strong> nach b um. A = <strong>${area} mm²</strong>, a = <strong>${a} mm</strong>.`, area/a, "mm", "Teile durch a.", "b = A / a", `${area} / ${a}`, rectDiagram(`${a} mm`, "b")); },
    (_, level) => { const [m,rho]=L(level,[60,2],[135,2.7],[270,2.7]); return E("Volumen aus Masse und Dichte", `Stelle <strong>m = rho · V</strong> nach V um. m = <strong>${m} g</strong>, rho = <strong>${N(rho)} g/cm³</strong>.`, m/rho, "cm³", "Teile durch die Dichte.", "V = m / rho", `${m} / ${N(rho)}`); },
    (_, level) => { const [m,V]=L(level,[80,40],[135,50],[270,100]); return E("Dichte freistellen", `Stelle <strong>m = rho · V</strong> nach rho um. m = <strong>${m} g</strong>, V = <strong>${V} cm³</strong>.`, m/V, "g/cm³", "Teile die Masse durch das Volumen.", "rho = m / V", `${m} / ${V}`); },
    (_, level) => { const [p,A]=L(level,[2,30],[4,45],[8,75]); return E("Kraft aus Pressung", `Stelle <strong>p = F / A</strong> nach F um. p = <strong>${p} N/mm²</strong>, A = <strong>${A} mm²</strong>.`, p*A, "N", "Multipliziere beide Seiten mit A.", "F = p · A", `${p} · ${A}`); },
    (_, level) => { const [sigma,A]=L(level,[5,20],[12,30],[25,40]); return E("Kraft aus Spannung", `Stelle <strong>sigma = F / A</strong> nach F um. sigma = <strong>${sigma} N/mm²</strong>, A = <strong>${A} mm²</strong>.`, sigma*A, "N", "Spannung mal Fläche ergibt Kraft.", "F = sigma · A", `${sigma} · ${A}`); },
    (_, level) => { const [F,s]=L(level,[40,10],[90,15],[180,30]); return E("Federrate freistellen", `Stelle <strong>F = R · s</strong> nach R um. F = <strong>${F} N</strong>, s = <strong>${s} mm</strong>.`, F/s, "N/mm", "Teile die Kraft durch den Federweg.", "R = F / s", `${F} / ${s}`); },
    (_, level) => { const [F,R]=L(level,[30,5],[84,7],[180,12]); return E("Federweg freistellen", `Stelle <strong>F = R · s</strong> nach s um. F = <strong>${F} N</strong>, R = <strong>${R} N/mm</strong>.`, F/R, "mm", "Teile die Kraft durch die Federrate.", "s = F / R", `${F} / ${R}`); },
    (_, level) => { const [vf,z,n]=L(level,[200,2,100],[480,4,120],[900,6,150]); return E("Zahnvorschub freistellen", `Stelle <strong>v_f = f_z · z · n</strong> nach f_z um. v_f = <strong>${vf} mm/min</strong>, z = <strong>${z}</strong>, n = <strong>${n} min⁻¹</strong>.`, vf/(z*n), "mm", "Teile durch z und n.", "f_z = v_f / (z · n)", `${vf} / (${z} · ${n})`); },
    (_, level) => { const [a,b]=L(level,[20,10],[35,15],[60,25]); const U=2*(a+b); return E("Seite aus Umfang", `Stelle <strong>U = 2 · (a + b)</strong> nach b um. U = <strong>${U} mm</strong>, a = <strong>${a} mm</strong>.`, b, "mm", "Teile zuerst den Umfang durch zwei.", "b = U / 2 − a", `${U} / 2 − ${a}`); },
    (_, level) => { const [l,b,h]=L(level,[10,5,4],[12,8,5],[20,10,6]); const V=l*b*h; return E("Höhe aus Volumen", `Stelle <strong>V = l · b · h</strong> nach h um. V = <strong>${V} cm³</strong>, l = <strong>${l} cm</strong>, b = <strong>${b} cm</strong>.`, h, "cm", "Teile das Volumen durch die Grundfläche.", "h = V / (l · b)", `${V} / (${l} · ${b})`, cuboidDiagram(`${l} cm`, `${b} cm`, "h")); }
  ],
  pythagoras: [
    (_, level) => { const k=L(level,1,2,3); return E("Drei-vier-fünf-Dreieck", `Ein rechtwinkliges Dreieck hat Katheten <strong>${3*k} cm</strong> und <strong>${4*k} cm</strong>. Berechne die schräge Seite.`, 5*k, "cm", "Die schräge Seite ist die Hypotenuse.", "c = √(a² + b²)", `√(${3*k}² + ${4*k}²)`, triangleDiagram(`${3*k} cm`, `${4*k} cm`, "c")); },
    (_, level) => { const k=L(level,1,2,3); return E("Kurze Kathete", `Hypotenuse: <strong>${13*k} cm</strong>, eine Kathete: <strong>${12*k} cm</strong>. Wie lang ist die andere Kathete?`, 5*k, "cm", "Ziehe das Quadrat der bekannten Kathete ab.", "a = √(c² − b²)", `√(${13*k}² − ${12*k}²)`, triangleDiagram("a", `${12*k} cm`, `${13*k} cm`)); },
    (_, level) => { const k=L(level,1,2,3); return E("Strebe über Eck", `Eine Strebe überbrückt <strong>${8*k} m</strong> waagerecht und <strong>${15*k} m</strong> senkrecht. Wie lang ist sie?`, 17*k, "m", "Waagerecht und senkrecht bilden einen rechten Winkel.", "c = √(a² + b²)", `√(${8*k}² + ${15*k}²)`, triangleDiagram(`${8*k} m`, `${15*k} m`, "c")); },
    (_, level) => { const k=L(level,1,2,3); return E("Leiter an der Wand", `Eine Leiter ist <strong>${10*k} m</strong> lang. Ihr Fuß steht <strong>${6*k} m</strong> von der Wand entfernt. Welche Höhe erreicht sie?`, 8*k, "m", "Die Leiter ist die Hypotenuse.", "h = √(c² − a²)", `√(${10*k}² − ${6*k}²)`, triangleDiagram(`${6*k} m`, "h", `${10*k} m`)); },
    (_, level) => { const k=L(level,1,2,3); return E("Schnur über ein Rechteck", `Ein rechteckiger Rahmen misst <strong>${9*k} cm × ${12*k} cm</strong>. Wie lang ist eine Schnur von Ecke zu Ecke?`, 15*k, "cm", "Die Schnur ist die Diagonale.", "d = √(a² + b²)", `√(${9*k}² + ${12*k}²)`, triangleDiagram(`${9*k} cm`, `${12*k} cm`, "d")); },
    (_, level) => { const x=L(level,20,40,80); return E("Winkel bei gleicher Höhe und Länge", `Eine Schräge steigt um <strong>${x} mm</strong> auf <strong>${x} mm</strong> waagerechter Länge. Wie groß ist der Winkel zur Waagerechten?`, 45, "°", "Gegenkathete und Ankathete sind gleich lang.", "tan(alpha) = Gegenkathete / Ankathete = 1", "arctan(1)", triangleDiagram(`${x} mm`, `${x} mm`, "")); },
    (_, level) => { const x=L(level,20,40,80); return E("Höhe bei 45 Grad", `Eine Schräge läuft <strong>${x} mm</strong> waagerecht und hat einen Winkel von <strong>45°</strong>. Wie hoch steigt sie?`, x, "mm", "Bei 45° sind beide Katheten gleich lang.", "h = a · tan(45°)", `${x} · 1`, triangleDiagram(`${x} mm`, "h", "")); },
    (_, level) => { const c=L(level,20,40,80); return E("Höhe bei 30 Grad", `Eine Strebe ist <strong>${c} cm</strong> lang und liegt <strong>30°</strong> über der Waagerechten. Wie hoch reicht sie?`, c/2, "cm", "sin(30°) = 0,5.", "h = c · sin(30°)", `${c} · 0,5`, triangleDiagram("", "h", `${c} cm`)); },
    (_, level) => { const c=L(level,20,40,80); return E("Waagerechte bei 60 Grad", `Eine Strebe ist <strong>${c} cm</strong> lang und liegt <strong>60°</strong> zur Waagerechten. Wie groß ist die waagerechte Strecke?`, c/2, "cm", "cos(60°) = 0,5.", "a = c · cos(60°)", `${c} · 0,5`, triangleDiagram("a", "", `${c} cm`)); },
    (_, level) => { const h=L(level,8,15,25); return E("Strebe aus Höhe bei 30 Grad", `Eine Strebe bildet <strong>30°</strong> mit der Waagerechten. Ihre senkrechte Höhe beträgt <strong>${h} mm</strong>. Wie lang ist die Strebe?`, h*2, "mm", "sin(30°) = 0,5.", "c = h / sin(30°)", `${h} / 0,5`, triangleDiagram("", `${h} mm`, "c")); },
    (_, level) => { const a=L(level,10,20,40); return E("Strebe aus Länge bei 60 Grad", `Eine Strebe bildet <strong>60°</strong> mit der Waagerechten. Der waagerechte Abstand beträgt <strong>${a} mm</strong>. Wie lang ist die Strebe?`, a*2, "mm", "cos(60°) = 0,5.", "c = a / cos(60°)", `${a} / 0,5`, triangleDiagram(`${a} mm`, "", "c")); },
    (_, level) => { const a=L(level,30,45,60); return E("Zweiter spitzer Winkel", `Ein rechtwinkliges Dreieck hat einen spitzen Winkel von <strong>${a}°</strong>. Wie groß ist der andere spitze Winkel?`, 90-a, "°", "Die zwei spitzen Winkel ergeben zusammen 90°.", "beta = 90° − alpha", `90 − ${a}`, triangleDiagram("", "", "")); }
  ],
  flaechen: [
    (_, level) => { const a=L(level,5,8,12); return E("Quadratische Platte", `Eine quadratische Platte hat Seitenlänge <strong>${a} cm</strong>. Berechne ihre Fläche.`, a*a, "cm²", "Beim Quadrat sind Länge und Breite gleich.", "A = a²", `${a} · ${a}`, rectDiagram(`${a} cm`, `${a} cm`)); },
    (_, level) => { const [g,h]=L(level,[10,4],[15,6],[24,8]); return E("Parallelogramm", `Ein Parallelogramm hat Grundseite <strong>${g} cm</strong> und senkrechte Höhe <strong>${h} cm</strong>. Berechne A.`, g*h, "cm²", "Nimm die senkrechte Höhe, nicht die schräge Seite.", "A = g · h", `${g} · ${h}`); },
    (_, level) => { const [a,c,h]=L(level,[8,4,5],[14,6,8],[20,10,12]); return E("Trapezfläche", `Ein Trapez hat die parallelen Seiten <strong>${a} cm</strong> und <strong>${c} cm</strong> sowie Höhe <strong>${h} cm</strong>. Berechne A.`, (a+c)*h/2, "cm²", "Addiere zuerst die parallelen Seiten.", "A = (a + c) · h / 2", `(${a} + ${c}) · ${h} / 2`); },
    (_, level) => { const [a,b]=L(level,[6,8],[10,12],[14,16]); return E("Halbes Rechteck", `Ein rechteckiges Blech <strong>${a} cm × ${b} cm</strong> wird diagonal halbiert. Wie groß ist eine Hälfte?`, a*b/2, "cm²", "Die Diagonale teilt das Rechteck in zwei gleich große Dreiecke.", "A = a · b / 2", `${a} · ${b} / 2`, triangleDiagram(`${a} cm`, `${b} cm`, "")); },
    (_, level) => { const r=L(level,2,4,6); return E("Halbkreis", `Ein Halbkreis hat Radius <strong>${r} cm</strong>. Berechne seine Fläche mit π ≈ 3,14.`, Math.PI*r*r/2, "cm²", "Berechne erst den ganzen Kreis und halbiere.", "A = π · r² / 2", `π · ${r}² / 2`, "", 2); },
    (_, level) => { const r=L(level,4,8,12); return E("Viertelkreis", `Ein Viertelkreis hat Radius <strong>${r} cm</strong>. Berechne seine Fläche.`, Math.PI*r*r/4, "cm²", "Ein Viertelkreis ist ein Viertel der Kreisfläche.", "A = π · r² / 4", `π · ${r}² / 4`, "", 2); },
    (_, level) => { const [a,b,s]=L(level,[8,6,2],[12,8,3],[20,12,4]); return E("Platte mit quadratischer Aussparung", `Eine Platte misst <strong>${a} cm × ${b} cm</strong>. Ein Quadrat mit Seitenlänge <strong>${s} cm</strong> wird entfernt. Wie groß bleibt die Fläche?`, a*b-s*s, "cm²", "Ziehe die kleine Quadratfläche von der Platte ab.", "A = a · b − s²", `${a} · ${b} − ${s}²`); },
    (_, level) => { const [a,b,c,d]=L(level,[8,4,4,2],[12,5,6,3],[20,8,8,4]); return E("L-förmige Fläche", `Eine L-Form besteht aus Rechteck 1 (<strong>${a} cm × ${b} cm</strong>) und Rechteck 2 (<strong>${c} cm × ${d} cm</strong>). Sie überlappen nicht. Wie groß ist die Fläche?`, a*b+c*d, "cm²", "Addiere die beiden Rechteckflächen.", "A = a · b + c · d", `${a} · ${b} + ${c} · ${d}`); },
    (_, level) => { const [n,a,b]=L(level,[3,10,2],[4,15,3],[5,20,4]); return E("Mehrere gleiche Bleche", `Es liegen <strong>${n}</strong> Bleche mit je <strong>${a} cm × ${b} cm</strong> bereit. Wie groß ist ihre Gesamtfläche?`, n*a*b, "cm²", "Erst die Fläche eines Blechs, dann mit der Anzahl multiplizieren.", "A_gesamt = n · a · b", `${n} · ${a} · ${b}`); },
    (_, level) => { const [A,g]=L(level,[30,10],[72,12],[150,20]); return E("Dreieckshöhe berechnen", `Ein Dreieck hat A = <strong>${A} cm²</strong> und Grundseite g = <strong>${g} cm</strong>. Wie groß ist die Höhe?`, 2*A/g, "cm", "Verdopple die Fläche und teile durch die Grundseite.", "h = 2 · A / g", `2 · ${A} / ${g}`, triangleDiagram(`${g} cm`, "h", "")); },
    (_, level) => { const r=L(level,3,5,10); return E("Kreis mit Radius", `Ein Kreis hat Radius <strong>${r} cm</strong>. Berechne seine Fläche.`, Math.PI*r*r, "cm²", "Der Radius wird quadriert.", "A = π · r²", `π · ${r}²`, "", 2); },
    (_, level) => { const [a,b,g,h]=L(level,[10,4,6,4],[16,6,8,6],[20,8,10,8]); return E("Rechteck mit Dreieck", `Eine Fläche besteht aus einem Rechteck (<strong>${a} cm × ${b} cm</strong>) und einem aufgesetzten Dreieck (g = <strong>${g} cm</strong>, h = <strong>${h} cm</strong>). Wie groß ist sie?`, a*b+g*h/2, "cm²", "Berechne beide Teilflächen getrennt.", "A = a · b + g · h / 2", `${a} · ${b} + ${g} · ${h} / 2`); }
  ],
  volumen: [
    (_, level) => { const a=L(level,4,6,10); return E("Würfelvolumen", `Ein Würfel hat Kantenlänge <strong>${a} cm</strong>. Wie groß ist sein Volumen?`, a*a*a, "cm³", "Alle drei Kanten sind gleich lang.", "V = a³", `${a} · ${a} · ${a}`, cuboidDiagram(`${a} cm`, `${a} cm`, `${a} cm`)); },
    (_, level) => { const [n,l,b,h]=L(level,[2,5,4,3],[3,8,5,4],[4,10,6,5]); return E("Volumen mehrerer Blöcke", `Es gibt <strong>${n}</strong> gleiche Blöcke mit je <strong>${l} cm × ${b} cm × ${h} cm</strong>. Berechne das Gesamtvolumen.`, n*l*b*h, "cm³", "Berechne zuerst das Volumen eines Blocks.", "V_gesamt = n · l · b · h", `${n} · ${l} · ${b} · ${h}`); },
    (_, level) => { const [D,d,h]=L(level,[6,2,10],[8,4,12],[10,6,15]); return E("Hohlzylinder", `Ein Rohr hat Außendurchmesser <strong>${D} cm</strong>, Innendurchmesser <strong>${d} cm</strong> und Länge <strong>${h} cm</strong>. Wie groß ist das Materialvolumen?`, Math.PI*(D*D-d*d)*h/4, "cm³", "Außenzylinder minus Innenzylinder.", "V = π · (D² − d²) · h / 4", `π · (${D}² − ${d}²) · ${h} / 4`, "", 2); },
    (_, level) => { const [r,h]=L(level,[2,5],[3,8],[4,10]); return E("Zylinder mit Radius", `Ein Zylinder hat Radius <strong>${r} cm</strong> und Höhe <strong>${h} cm</strong>. Wie groß ist sein Volumen?`, Math.PI*r*r*h, "cm³", "Kreisfläche mal Höhe.", "V = π · r² · h", `π · ${r}² · ${h}`, "", 2); },
    (_, level) => { const [g,h,l]=L(level,[6,4,10],[8,6,12],[10,8,15]); return E("Dreiecksprisma", `Ein Prisma hat eine dreieckige Grundfläche (g = <strong>${g} cm</strong>, h = <strong>${h} cm</strong>) und Länge <strong>${l} cm</strong>. Berechne V.`, g*h*l/2, "cm³", "Dreiecksfläche mal Länge.", "V = g · h · l / 2", `${g} · ${h} · ${l} / 2`); },
    (_, level) => { const [r,h]=L(level,[3,9],[4,12],[5,15]); return E("Kegelvolumen", `Ein Kegel hat Radius <strong>${r} cm</strong> und Höhe <strong>${h} cm</strong>. Wie groß ist sein Volumen?`, Math.PI*r*r*h/3, "cm³", "Der Kegel hat ein Drittel des entsprechenden Zylindervolumens.", "V = π · r² · h / 3", `π · ${r}² · ${h} / 3`, "", 2); },
    (_, level) => { const V=L(level,10,20,50); return E("Masse von Aluminium", `Ein Aluminiumteil hat Volumen <strong>${V} cm³</strong>. Rechne mit Dichte <strong>2,7 g/cm³</strong>. Wie groß ist die Masse?`, V*2.7, "g", "Dichte mal Volumen ergibt Masse.", "m = rho · V", `2,7 · ${V}`); },
    (_, level) => { const V=L(level,100,200,400); return E("Stahlmasse in Kilogramm", `Ein Stahlteil hat Volumen <strong>${V} cm³</strong>. Rechne mit Dichte <strong>7,85 g/cm³</strong>. Gib die Masse in kg an.`, V*7.85/1000, "kg", "Rechne erst Gramm, danach durch 1000 teilen.", "m_kg = rho · V / 1000", `7,85 · ${V} / 1000`); },
    (_, level) => { const [m,V]=L(level,[54,20],[135,50],[270,100]); return E("Dichte aus Masse", `Ein Teil hat Masse <strong>${m} g</strong> und Volumen <strong>${V} cm³</strong>. Berechne die Dichte.`, m/V, "g/cm³", "Dichte ist Masse durch Volumen.", "rho = m / V", `${m} / ${V}`); },
    (_, level) => { const [before,after]=L(level,[50,80],[100,145],[150,225]); return E("Wasserverdrängung", `In einem Messbecher sind zuerst <strong>${before} ml</strong> Wasser, nach dem Eintauchen eines Teils <strong>${after} ml</strong>. Wie groß ist das Volumen des Teils?`, after-before, "cm³", "Die Wasserdifferenz entspricht dem Teilvolumen.", "1 ml = 1 cm³", `${after} − ${before}`); },
    (_, level) => { const [l,b,h]=L(level,[20,10,5],[25,20,10],[40,25,10]); return E("Behälter in Litern", `Ein rechteckiger Behälter misst innen <strong>${l} cm × ${b} cm × ${h} cm</strong>. Wie viele Liter fasst er?`, l*b*h/1000, "l", "Berechne cm³ und teile durch 1000.", "1 l = 1000 cm³", `${l} · ${b} · ${h} / 1000`, cuboidDiagram(`${l} cm`, `${b} cm`, `${h} cm`)); },
    (_, level) => { const [V,A]=L(level,[120,20],[360,30],[750,50]); return E("Stablänge aus Volumen", `Ein Stab hat Querschnitt <strong>${A} cm²</strong> und Volumen <strong>${V} cm³</strong>. Wie lang ist er?`, V/A, "cm", "Volumen ist Querschnitt mal Länge.", "l = V / A", `${V} / ${A}`); }
  ],
  bewegung: [
    (_, level) => { const [v,t]=L(level,[3,10],[5,12],[8,25]); return E("Weg eines Transportwagens", `Ein Wagen fährt mit <strong>${v} m/s</strong> während <strong>${t} s</strong>. Welche Strecke legt er zurück?`, v*t, "m", "Geschwindigkeit mal Zeit ergibt Weg.", "s = v · t", `${v} · ${t}`); },
    (_, level) => { const [s,v]=L(level,[60,5],[144,8],[360,12]); return E("Fahrzeit in Sekunden", `Ein Wagen fährt <strong>${s} m</strong> mit <strong>${v} m/s</strong>. Wie viele Sekunden braucht er?`, s/v, "s", "Teile den Weg durch die Geschwindigkeit.", "t = s / v", `${s} / ${v}`); },
    (_, level) => { const [n,t]=L(level,[60,2],[120,3],[250,4]); return E("Umdrehungen zählen", `Eine Spindel dreht sich mit <strong>${n} U/min</strong> für <strong>${t} min</strong>. Wie viele Umdrehungen sind das?`, n*t, "U", "Drehzahl mal Zeit ergibt Umdrehungen.", "U = n · t", `${n} · ${t}`); },
    (_, level) => { const [s,vf]=L(level,[100,50],[240,80],[600,120]); return E("Bearbeitungszeit", `Ein Werkzeug fährt <strong>${s} mm</strong> mit Vorschubgeschwindigkeit <strong>${vf} mm/min</strong>. Wie viele Minuten dauert das?`, s/vf, "min", "Weg geteilt durch Geschwindigkeit gibt die Zeit.", "t = s / v_f", `${s} / ${vf}`); },
    (_, level) => { const [f,n]=L(level,[0.2,100],[0.25,200],[0.4,250]); return E("Vorschub pro Minute", `Der Vorschub pro Umdrehung beträgt <strong>${N(f)} mm/U</strong>, die Drehzahl <strong>${n} U/min</strong>. Berechne den Vorschub pro Minute.`, f*n, "mm/min", "Pro Umdrehung mal Umdrehungen pro Minute.", "v_f = f · n", `${N(f)} · ${n}`); },
    (_, level) => { const [vf,n]=L(level,[20,100],[50,200],[100,250]); return E("Vorschub je Umdrehung", `Ein Werkzeug fährt mit <strong>${vf} mm/min</strong> bei <strong>${n} U/min</strong>. Wie viele mm Vorschub hat es pro Umdrehung?`, vf/n, "mm/U", "Teile den Minutenvorschub durch die Drehzahl.", "f = v_f / n", `${vf} / ${n}`); },
    (_, level) => { const [vf,f]=L(level,[40,0.2],[100,0.25],[200,0.4]); return E("Drehzahl aus Vorschub", `Ein Werkzeug fährt mit <strong>${vf} mm/min</strong>. Vorschub je Umdrehung: <strong>${N(f)} mm/U</strong>. Berechne die Drehzahl.`, vf/f, "U/min", "Teile den Minutenvorschub durch den Vorschub je Umdrehung.", "n = v_f / f", `${vf} / ${N(f)}`); },
    (_, level) => { const d=L(level,10,20,40); return E("Weg pro Radumdrehung", `Ein Rad hat Durchmesser <strong>${d} cm</strong>. Wie weit rollt es bei einer Umdrehung?`, Math.PI*d, "cm", "Der Weg ist ein Umfang.", "U = π · d", `π · ${d}`, circleDiagram(`d=${d}`), 2); },
    (_, level) => { const [d,n]=L(level,[10,2],[20,3],[40,5]); return E("Rollweg nach mehreren Umdrehungen", `Ein Rad mit Durchmesser <strong>${d} cm</strong> rollt <strong>${n}</strong> Umdrehungen. Wie weit rollt es?`, Math.PI*d*n, "cm", "Eine Umdrehung entspricht einem Umfang.", "s = π · d · U", `π · ${d} · ${n}`, circleDiagram(`d=${d}`), 2); },
    (_, level) => { const [s1,s2,t]=L(level,[20,40,10],[50,70,12],[90,150,20]); return E("Mittlere Geschwindigkeit", `Ein Wagen legt erst <strong>${s1} m</strong>, dann <strong>${s2} m</strong> zurück. Insgesamt braucht er <strong>${t} s</strong>. Wie groß ist die mittlere Geschwindigkeit?`, (s1+s2)/t, "m/s", "Addiere zuerst beide Wege.", "v_mittel = Gesamtweg / Gesamtzeit", `(${s1} + ${s2}) / ${t}`); },
    (_, level) => { const [v1,v2,t]=L(level,[2,8,3],[4,16,4],[5,25,5]); return E("Beschleunigung", `Ein Wagen wird in <strong>${t} s</strong> von <strong>${v1} m/s</strong> auf <strong>${v2} m/s</strong> schneller. Berechne die Beschleunigung.`, (v2-v1)/t, "m/s²", "Erst die Änderung der Geschwindigkeit berechnen.", "a = (v_2 − v_1) / t", `(${v2} − ${v1}) / ${t}`); },
    (_, level) => { const [n1,z1,z2]=L(level,[100,20,40],[150,30,50],[240,25,60]); return E("Drehzahl mit Zahnrädern", `Ein Zahnrad mit <strong>${z1}</strong> Zähnen dreht sich mit <strong>${n1} U/min</strong>. Es treibt eines mit <strong>${z2}</strong> Zähnen an. Wie groß ist dessen Drehzahl?`, n1*z1/z2, "U/min", "Mehr Zähne am Abtrieb bedeuten eine kleinere Drehzahl.", "n_2 = n_1 · z_1 / z_2", `${n1} · ${z1} / ${z2}`); }
  ],
  kraefte: [
    (_, level) => { const F=L(level,50,120,250); return E("Masse aus Gewichtskraft", `Ein Körper hat Gewichtskraft <strong>${F} N</strong>. Rechne überschlägig mit g = <strong>10 N/kg</strong>. Wie groß ist die Masse?`, F/10, "kg", "Gewichtskraft durch Erdbeschleunigung teilen.", "m = F_G / g", `${F} / 10`); },
    (_, level) => { const [p,A]=L(level,[2,20],[5,40],[12,75]); return E("Kraft aus Druck", `Auf eine Fläche von <strong>${A} mm²</strong> wirken <strong>${p} N/mm²</strong> Druck. Wie groß ist die Kraft?`, p*A, "N", "Druck mal Fläche ergibt Kraft.", "F = p · A", `${p} · ${A}`); },
    (_, level) => { const [F,sigma]=L(level,[100,5],[300,10],[750,15]); return E("Mindestquerschnitt", `Eine Kraft von <strong>${F} N</strong> darf höchstens <strong>${sigma} N/mm²</strong> Spannung erzeugen. Wie groß muss der Querschnitt mindestens sein?`, F/sigma, "mm²", "Größere Fläche senkt die Spannung.", "A = F / sigma", `${F} / ${sigma}`); },
    (_, level) => { const [F1,F2,l2]=L(level,[20,40,10],[30,60,15],[40,100,20]); return E("Hebelarm finden", `Ein Hebel ist im Gleichgewicht: F₁ = <strong>${F1} N</strong>, F₂ = <strong>${F2} N</strong>, l₂ = <strong>${l2} cm</strong>. Wie lang ist l₁?`, F2*l2/F1, "cm", "Beide Drehmomente sind gleich.", "l_1 = F_2 · l_2 / F_1", `${F2} · ${l2} / ${F1}`); },
    (_, level) => { const [F1,l1,l2]=L(level,[40,20,10],[60,30,15],[100,40,20]); return E("Last am Hebel", `Ein Hebel ist im Gleichgewicht: F₁ = <strong>${F1} N</strong>, l₁ = <strong>${l1} cm</strong>, l₂ = <strong>${l2} cm</strong>. Berechne F₂.`, F1*l1/l2, "N", "Langer Arm mal kleine Kraft kann kurzen Arm ausgleichen.", "F_2 = F_1 · l_1 / l_2", `${F1} · ${l1} / ${l2}`); },
    (_, level) => { const [F,R]=L(level,[30,5],[84,7],[180,12]); return E("Federweg aus Kraft", `Eine Feder hat Federrate <strong>${R} N/mm</strong>. Sie wird mit <strong>${F} N</strong> belastet. Wie weit wird sie zusammengedrückt?`, F/R, "mm", "Kraft durch Federrate teilen.", "s = F / R", `${F} / ${R}`); },
    (_, level) => { const [F,s]=L(level,[40,8],[90,15],[180,20]); return E("Federrate bestimmen", `Eine Feder braucht <strong>${F} N</strong> für <strong>${s} mm</strong> Weg. Wie groß ist ihre Federrate?`, F/s, "N/mm", "Kraft pro Millimeter Weg.", "R = F / s", `${F} / ${s}`); },
    (_, level) => { const [R1,R2,s]=L(level,[2,3,4],[3,5,5],[5,7,10]); return E("Zwei Federn parallel", `Zwei parallele Federn haben Federraten <strong>${R1} N/mm</strong> und <strong>${R2} N/mm</strong>. Beide werden um <strong>${s} mm</strong> gedrückt. Wie groß ist die gesamte Kraft?`, (R1+R2)*s, "N", "Bei parallelen Federn addieren sich die Kräfte.", "F = (R_1 + R_2) · s", `(${R1} + ${R2}) · ${s}`); },
    (_, level) => { const F=L(level,100,240,500); return E("Zwei gleiche Auflager", `Eine mittige Last von <strong>${F} N</strong> liegt auf zwei gleichen Auflagern. Welche Kraft trägt jedes Auflager?`, F/2, "N", "Die Last verteilt sich hier gleichmäßig.", "F_Auflager = F / 2", `${F} / 2`); },
    (_, level) => { const [F,l]=L(level,[20,0.5],[40,0.75],[80,1.25]); return E("Drehmoment", `Eine Kraft von <strong>${F} N</strong> wirkt senkrecht auf einen Hebelarm von <strong>${N(l)} m</strong>. Berechne das Drehmoment.`, F*l, "N·m", "Kraft mal senkrechter Hebelarm.", "M = F · l", `${F} · ${N(l)}`); },
    (_, level) => { const [F,A]=L(level,[100,20],[300,30],[800,40]); return E("Spannung in MPa", `Ein Stab wird mit <strong>${F} N</strong> belastet. Sein Querschnitt beträgt <strong>${A} mm²</strong>. Gib die Spannung in MPa an.`, F/A, "MPa", "1 N/mm² entspricht 1 MPa.", "sigma = F / A", `${F} / ${A}`); },
    (_, level) => { const [F,A]=L(level,[200,2],[500,5],[1200,8]); return E("Pressung auf Quadratzentimeter", `Eine Kraft von <strong>${F} N</strong> wirkt auf <strong>${A} cm²</strong>. Wie groß ist die Pressung in N/mm²?`, F/(A*100), "N/mm²", "1 cm² entspricht 100 mm².", "p = F / (A · 100)", `${F} / (${A} · 100)`); }
  ]
};
